version: 2

models:
  - name: stg_github_events
    description: Raw GitHub events from the last 7 days
    columns:
      - name: id
        tests:
          - not_null
      - name: type
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null

  - name: stg_github_pushes
    description: Push events with bots filtered out
    columns:
      - name: push_id
        tests:
          - not_null
      - name: repo_name
        tests:
          - not_null
      - name: actor_name
        tests:
          - not_null

  - name: developer_activity_metrics
    description: Developer stats including push counts, active days, streaks, and activity tiers
    columns:
      - name: actor_name
        tests:
          - not_null
          - unique
      - name: total_pushes
        tests:
          - not_null
      - name: developer_tier
        tests:
          - accepted_values:
              values: ['power_user', 'regular', 'casual']

  - name: repository_health_scores
    description: Repository health scoring based on contributor activity, retention, and velocity
    columns:
      - name: repo_name
        tests:
          - not_null
          - unique
      - name: health_score
        tests:
          - not_null
      - name: health_tier
        tests:
          - accepted_values:
              values: ['thriving', 'healthy', 'at_risk', 'declining']

  - name: contribution_patterns
    description: Activity heatmap by hour and day of week
    columns:
      - name: hour_of_day
        tests:
          - not_null
      - name: day_of_week
        tests:
          - not_null

  - name: event_type_trends
    description: Daily event counts by type for trend visualization
    columns:
      - name: event_date
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null

  - name: daily_activity
    description: Daily event counts by type

  - name: event_breakdown
    description: Total events by type
